---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    pvc: dp-pvc
  name: dp-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      mypv: dp-pv
status: {}
